import torch

import warp as wp
import newton
from newton import Contacts, GeoType, ShapeFlags
from isaaclab_neural.utils.warp_utils import device_to_torch
from isaaclab_neural.contacts.contact_utils import find_ground_shape_index
from isaaclab_neural.contacts.kernels import generate_contact_points

class AbstractContact:
    """
    Class for AbstractContact, a torch view of the rigid contact info in warp model

    Each contact is represented by:
    - contact_shape0 (fixed): a shape from robot
    - contact_point0 (fixed): the contact point in the shape0's body's frame
    - contact_shape1 (variable, fixed for now): a shape from the external object
    - contact_point1 (variable): the contact point in the shape1's body frame, or in world frame (for ground)
    - contact_normal (variable, fixed for now): the contact normal in world frame
    """
    def __init__(self, model: newton.Model):
        self.device = device_to_torch(model.device)

        self.contact_mode = "fixed_ground"

        assert model.shape_count > model.world_count, "There should be at least one shape for each world"

        self.num_envs = model.world_count

        # Detect ground shape index
        self.ground_shape_index = find_ground_shape_index(model)
        self.has_ground = self.ground_shape_index >= 0

        # Compute the offset where per-env shapes start.
        # In code-newton, ground is the last shape: shapes_start_offset = 0
        # In IsaacLab, ground is the first shape (index 0): shapes_start_offset = 1
        if self.has_ground and self.ground_shape_index == 0:
            self.shapes_start_offset = 1
        else:
            self.shapes_start_offset = 0

        # Step 1: count the number of contacts per env
        self.num_contacts_per_env = self.count_contacts(model)

        self.num_total_contacts = self.num_contacts_per_env * self.num_envs

        # Step 2: create the torch buffer for the abstract contacts
        self.create_abstract_contacts_buffer()

        # Step 3: create the newton.Contacts view of the torch buffers
        self.newton_contacts = self.create_newton_contacts_view()

        # Step 4: generate the values for the contacts
        self.initialize_contacts(model, self.newton_contacts)

    def count_contacts(self, model: newton.Model):
        """Count the number of contacts per env based on the anchors generated by generate_contact_points."""
        
        # Number of non-ground shapes divided by world_count
        num_non_ground_shapes = model.shape_count - (1 if self.has_ground else 0)
        num_shapes_per_env = num_non_ground_shapes // model.world_count

        geo_types = model.shape_type.numpy()
        shape_body = model.shape_body.numpy()
        shape_flags = model.shape_flags.numpy()

        num_contacts_per_env = 0

        # Iterate over the first env's shapes (starting after ground offset)
        for i in range(num_shapes_per_env):
            shape_idx = self.shapes_start_offset + i
            # static shapes are ignored, e.g. ground
            if shape_body[shape_idx] == -1:
                continue
            # filter out visual meshes
            if shape_flags[shape_idx] & int(ShapeFlags.COLLIDE_SHAPES) == 0:
                continue

            geo_type = geo_types[shape_idx]
            if geo_type == GeoType.SPHERE:
                num_contacts_per_env += 1
            elif geo_type == GeoType.CAPSULE:
                num_contacts_per_env += 2
            elif geo_type == GeoType.CYLINDER:
                # Capsule treatment: 2 endpoint anchors. See docs/design/CYLINDER_CONTACT_FIX.md.
                num_contacts_per_env += 2
            elif geo_type == GeoType.BOX:
                num_contacts_per_env += 8
            else: # NOTE: temporary COM fallback for mesh / unknown shapes
                num_contacts_per_env += 1

        return num_contacts_per_env

    # Create the torch buffer for the abstract contacts
    def create_abstract_contacts_buffer(self):
        # essential variables
        self.contact_shape0 = torch.empty(
            (self.num_total_contacts,),
            dtype = torch.int32,
            device = self.device
        )
        self.contact_shape1 = torch.empty(
            (self.num_total_contacts,),
            dtype = torch.int32,
            device = self.device
        )
        self.contact_point0 = torch.empty(
            (self.num_total_contacts, 3),
            dtype = torch.float32,
            device = self.device
        )
        self.contact_point1 = torch.empty(
            (self.num_total_contacts, 3),
            dtype = torch.float32,
            device = self.device
        )
        self.contact_normal = torch.empty(
            (self.num_total_contacts, 3),
            dtype = torch.float32,
            device = self.device
        )
        self.contact_thickness0 = torch.empty(
            (self.num_total_contacts,),
            dtype = torch.float32,
            device = self.device
        )
        self.contact_thickness1= torch.empty(
            (self.num_total_contacts,),
            dtype = torch.float32,
            device = self.device
        )

        #  derived variables (not used by newton default solvers)
        self.contact_depth = torch.empty(
            (self.num_total_contacts,),
            dtype = torch.float32,
            device = self.device
        )

    # create newton.Contacts
    # the fields of created newton contacts share the same memory with abstract_contacts
    def create_newton_contacts_view(self):
        warp_device = wp.device_from_torch(self.device)

        contacts = Contacts(
            rigid_contact_max = self.num_total_contacts,
            soft_contact_max = 0,
            requires_grad = False,
            device=warp_device
        )

        contacts.rigid_contact_count = wp.array(
            [self.num_total_contacts],
            dtype=wp.int32,
            device=warp_device
        )

        contacts.rigid_contact_shape0 = wp.from_torch(
            self.contact_shape0
        )
        contacts.rigid_contact_point0 = wp.from_torch(
            self.contact_point0,
            dtype = wp.vec3
        )
        contacts.rigid_contact_shape1 = wp.from_torch(
            self.contact_shape1
        )
        contacts.rigid_contact_point1 = wp.from_torch(
            self.contact_point1,
            dtype = wp.vec3
        )
        contacts.rigid_contact_normal = wp.from_torch(
            self.contact_normal,
            dtype = wp.vec3
        )
        contacts.rigid_contact_depth = wp.from_torch(
            self.contact_depth
        )
        contacts.rigid_contact_thickness0 = wp.from_torch(
            self.contact_thickness0
        )
        contacts.rigid_contact_thickness1 = wp.from_torch(
            self.contact_thickness1
        )

        return contacts

    # Fill the contacts buffers with the values
    def initialize_contacts(
        self,
        model: newton.Model,
        newton_contacts: newton.Contacts
    ):
        num_non_ground_shapes = model.shape_count - (1 if self.has_ground else 0)
        num_shapes_per_env = num_non_ground_shapes // model.world_count

        wp.launch(
            generate_contact_points,
            dim=model.world_count,
            inputs=[
                model.shape_transform,
                model.shape_body,
                model.shape_type,
                model.shape_scale,
                model.shape_margin,
                model.shape_flags,
                num_shapes_per_env,
                self.num_contacts_per_env,
                self.ground_shape_index,
                self.shapes_start_offset,
                model.up_axis.to_vec3(),
            ],
            outputs=[
                newton_contacts.rigid_contact_shape0,
                newton_contacts.rigid_contact_shape1,
                newton_contacts.rigid_contact_point0,
                newton_contacts.rigid_contact_point1,
                newton_contacts.rigid_contact_thickness0,
                newton_contacts.rigid_contact_thickness1,
                newton_contacts.rigid_contact_normal,
                newton_contacts.rigid_contact_depth,
            ],
            device=model.device,
        )