[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.0.1"

# Description
title = "Neural simulation interfaces for IsaacLab core package"
description="Extension providing IsaacLab with Neural simulation specific abstractions."
readme  = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["robotics", "neural simulation", "newton"]

[dependencies]
"isaaclab" = {}

[core]
reloadable = false

[[python.module]]
name = "isaaclab_neural"
